languageCode = "en"
languageName = "English"
weight = 1
title = "For Later Analysis"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "A powerful, lightweight theme for Hugo."

[params.author]
  name = "Vicki Mu"
  email = "vymu@mit.edu"
  image = "profile.png"
  headline = "Making sense of AI, physics, and the weird stuff in between."
  bio = "I’m a student at MIT exploring the edges of intelligence—building models, recreating ideas, and writing to figure out what I think."
  links = [
    { x-twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]